- name: restart postfix
  service:
    name: postfix
    state: restarted
  when: ansible_virtualization_type is not defined or ansible_virtualization_type != 'docker'

- name: exec newaliases
  command: /usr/bin/newaliases
