- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: ansible_virtualization_type is not defined or ansible_virtualization_type != 'docker'

- name: Exec newaliases
  ansible.builtin.command: /usr/bin/newaliases
  changed_when: false
