version: 2
jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - checkout

      - run:
          name: Build ansible
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}/ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
