version: 2
jobs:
  ansible-debian:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: ansible-debian
          command: |
            cd ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
  puppet-debian:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: puppet-debian
          command: |
            cd puppet
            bash -x standalone-puppet.sh -e furlongm@gmail.com
  salt-debian:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: salt-debian
          command: |
            cd saltstack
            echo https://github.com/saltstack/salt-bootstrap/issues/1353
            #bash -x standalone-salt.sh -e furlongm@gmail.com
  chef-debian:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: chef-debian
          command: |
            cd chef
            bash -x standalone-chef.sh -e furlongm@gmail.com
  ansible-ubuntu:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: ansible-ubuntu
          command: |
            cd ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
  puppet-ubuntu:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: puppet-ubuntu
          command: |
            cd puppet
            bash -x standalone-puppet.sh -e furlongm@gmail.com
  salt-ubuntu:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: salt-ubuntu
          command: |
            cd saltstack
            bash -x standalone-salt.sh -e furlongm@gmail.com
  chef-ubuntu:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: chef-ubuntu
          command: |
            cd chef
            bash -x standalone-chef.sh -e furlongm@gmail.com
  ansible-centos:
    docker:
      - image: centos:8
    steps:
      - checkout
      - run:
          name: ansible-centos
          command: |
            cd ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
  puppet-centos:
    docker:
      - image: centos:8
    steps:
      - checkout
      - run:
          name: puppet-centos
          command: |
            cd puppet
            bash -x standalone-puppet.sh -e furlongm@gmail.com
  salt-centos:
    docker:
      - image: centos:8
    steps:
      - checkout
      - run:
          name: salt-centos
          command: |
            cd saltstack
            echo https://github.com/saltstack/salt-bootstrap/issues/1371
            #bash -x standalone-salt.sh -e furlongm@gmail.com
  chef-centos:
    docker:
      - image: centos:8
    steps:
      - checkout
      - run:
          name: chef-centos
          command: |
            cd chef
            bash -x standalone-chef.sh -e furlongm@gmail.com
  ansible-opensuse:
    docker:
      - image: opensuse/leap:15.1
    steps:
      - checkout
      - run:
          name: ansible-opensuse
          command: |
            cd ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
  puppet-opensuse:
    docker:
      - image: opensuse/leap:15.1
    steps:
      - checkout
      - run:
          name: puppet-opensuse
          command: |
            cd puppet
            bash -x standalone-puppet.sh -e furlongm@gmail.com
  salt-opensuse:
    docker:
      - image: opensuse/leap:15.1
    steps:
      - checkout
      - run:
          name: salt-opensuse
          command: |
            cd saltstack
            bash -x standalone-salt.sh -e furlongm@gmail.com
  chef-opensuse:
    docker:
      - image: opensuse/leap:15.1
    steps:
      - checkout
      - run:
          name: chef-opensuse
          command: |
            cd chef
            echo https://github.com/chef/omnitruck/pull/375
            #bash -x standalone-chef.sh -e furlongm@gmail.com
  ansible-fedora:
    docker:
      - image: fedora:31
    steps:
      - checkout
      - run:
          name: ansible-fedora
          command: |
            cd ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
  puppet-fedora:
    docker:
      - image: fedora:31
    steps:
      - checkout
      - run:
          name: puppet-fedora
          command: |
            cd puppet
            bash -x standalone-puppet.sh -e furlongm@gmail.com
  salt-fedora:
    docker:
      - image: fedora:31
    steps:
      - checkout
      - run:
          name: salt-fedora
          command: |
            cd saltstack
            echo https://github.com/saltstack/salt/issues/55787
            #bash -x standalone-salt.sh -e furlongm@gmail.com
  chef-fedora:
    docker:
      - image: fedora:31
    steps:
      - checkout
      - run:
          name: chef-fedora
          command: |
            cd chef
            bash -x standalone-chef.sh -e furlongm@gmail.com

workflows:
  version: 2
  test-all-tool-distro-combos:
    jobs:
      - ansible-debian
      - ansible-ubuntu
      - ansible-centos
      - ansible-opensuse
      - ansible-fedora
      - puppet-debian
      - puppet-ubuntu
      - puppet-centos
      - puppet-opensuse
      - puppet-fedora
      - salt-debian
      - salt-ubuntu
      - salt-centos
      - salt-opensuse
      - salt-fedora
      - chef-debian
      - chef-ubuntu
      - chef-centos
      - chef-opensuse
      - chef-fedora
