version: 2
jobs:
  lint-ansible:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: ansible-lint
          command: |
            apt update
            apt -y install build-essential python3-virtualenv
            virtualenv ansible-lint
            . ansible-lint/bin/activate
            pip install ansible-lint
            cd ansible/playbooks/roles
            ansible-lint *
            deactivate
  lint-puppet:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: puppet-lint
          command: |
            apt update
            apt -y install build-essential zlib1g-dev ruby ruby-dev
            gem install puppet-lint
            puppet-lint --no-documentation-check puppet/modules
  lint-salt:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: salt-lint
          command: |
            apt update
            apt -y install build-essential python3-dev python3-virtualenv
            virtualenv salt-lint
            . salt-lint/bin/activate
            pip install salt-lint
            find saltstack -name "*.sls" -print0 | xargs -0 -n1 salt-lint
            deactivate
  lint-chef:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: chef-lint
          command: |
            apt update
            apt -y install build-essential zlib1g-dev ruby ruby-dev
            gem install foodcritic cookstyle
            foodcritic -t ~FC031 -t ~FC071 -t ~FC011 -t ~FC109 chef/cookbooks
            cookstyle chef
  ansible-debian:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: ansible-debian
          command: |
            cd ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
  puppet-debian:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: puppet-debian
          command: |
            cd puppet
            bash -x standalone-puppet.sh -e furlongm@gmail.com
  salt-debian:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: salt-debian
          command: |
            cd saltstack
            bash -x standalone-salt.sh -e furlongm@gmail.com
  chef-debian:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: chef-debian
          command: |
            cd chef
            bash -x standalone-chef.sh -e furlongm@gmail.com
  ansible-ubuntu:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: ansible-ubuntu
          command: |
            cd ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
  puppet-ubuntu:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: puppet-ubuntu
          command: |
            cd puppet
            bash -x standalone-puppet.sh -e furlongm@gmail.com
  salt-ubuntu:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: salt-ubuntu
          command: |
            cd saltstack
            bash -x standalone-salt.sh -e furlongm@gmail.com
  chef-ubuntu:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: chef-ubuntu
          command: |
            cd chef
            bash -x standalone-chef.sh -e furlongm@gmail.com
  ansible-centos:
    docker:
      - image: centos:8
    steps:
      - checkout
      - run:
          name: ansible-centos
          command: |
            cd ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
  puppet-centos:
    docker:
      - image: centos:8
    steps:
      - checkout
      - run:
          name: puppet-centos
          command: |
            cd puppet
            bash -x standalone-puppet.sh -e furlongm@gmail.com
  salt-centos:
    docker:
      - image: centos:8
    steps:
      - checkout
      - run:
          name: salt-centos
          command: |
            cd saltstack
            bash -x standalone-salt.sh -e furlongm@gmail.com
  chef-centos:
    docker:
      - image: centos:8
    steps:
      - checkout
      - run:
          name: chef-centos
          command: |
            cd chef
            bash -x standalone-chef.sh -e furlongm@gmail.com
  ansible-opensuse:
    docker:
      - image: opensuse/leap:15.2
    steps:
      - checkout
      - run:
          name: ansible-opensuse
          command: |
            cd ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
  puppet-opensuse:
    docker:
      - image: opensuse/leap:15.2
    steps:
      - checkout
      - run:
          name: puppet-opensuse
          command: |
            cd puppet
            bash -x standalone-puppet.sh -e furlongm@gmail.com
  salt-opensuse:
    docker:
      - image: opensuse/leap:15.2
    steps:
      - checkout
      - run:
          name: salt-opensuse
          command: |
            cd saltstack
            bash -x standalone-salt.sh -e furlongm@gmail.com
  chef-opensuse:
    docker:
      - image: opensuse/leap:15.2
    steps:
      - checkout
      - run:
          name: chef-opensuse
          command: |
            cd chef
            echo https://github.com/chef/omnitruck/pull/375
            #bash -x standalone-chef.sh -e furlongm@gmail.com
  ansible-fedora:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - run:
          name: ansible-fedora
          command: |
            cd ansible
            bash -x standalone-ansible.sh -e furlongm@gmail.com
  puppet-fedora:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - run:
          name: puppet-fedora
          command: |
            cd puppet
            bash -x standalone-puppet.sh -e furlongm@gmail.com
  salt-fedora:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - run:
          name: salt-fedora
          command: |
            cd saltstack
            echo https://github.com/saltstack/salt/issues/55787
            #bash -x standalone-salt.sh -e furlongm@gmail.com
  chef-fedora:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - run:
          name: chef-fedora
          command: |
            cd chef
            bash -x standalone-chef.sh -e furlongm@gmail.com

workflows:
  version: 2
  linters:
   jobs:
      - lint-ansible
      - lint-puppet
      - lint-salt
      - lint-chef
  test-tool-distro-combos:
    jobs:
      - ansible-debian
      - ansible-ubuntu
      - ansible-centos
      - ansible-opensuse
      - ansible-fedora
      - puppet-debian
      - puppet-ubuntu
      - puppet-centos
      - puppet-opensuse
      - puppet-fedora
      - salt-debian
      - salt-ubuntu
      - salt-centos
      - salt-opensuse
      - salt-fedora
      - chef-debian
      - chef-ubuntu
      - chef-centos
      - chef-opensuse
      - chef-fedora
