version: 2
jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - checkout

      - run:
          name: Build ansible
          command: |
            ls -la
            apt install -y tree
            tree
            bash -x ${CIRCLE_PROJECT_REPONAME}/standalone-ansible.sh -e furlongm@gmail.com
