- name: Set up distro vars
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Install net packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - tcpdump
    - nmap
    - telnet
    - iftop
    - whois
    - wget
    - ipset
    - nload
    - "{{ iperf_package }}"
    - "{{ bindutils_package }}"

- name: Don't install bmon on RHEL8
  package:
    name: "{{ item }}"
    state: present
  when: ansible_distribution_major_version != "8" and ansible_os_family != "RedHat"
  with_items:
    - bmon
