- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- package: name={{ item }} state=present
  with_items:
  - tcpdump
  - nmap
  - telnet
  - iftop
  - whois
  - wget
  - ipset
  - nload

- package: name={{ item }} state=present
  when: ansible_distribution_major_version != "8" and ansible_os_family != "RedHat"
  with_items:
  - iperf
  - bmon

- package: name={{ bindutils_package }} state=present
