- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- package: name={{ item }} state=present
  with_items:
    - tcpdump
    - nmap
    - telnet
    - iftop
    - whois
    - wget
    - ipset
    - nload
    - iperf3

- package: name={{ item }} state=present
  when: ansible_distribution_major_version != "8" and ansible_os_family != "RedHat"
  with_items:
    - bmon

- package: name={{ bindutils_package }} state=present
