- name: Set up distro vars
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- import_tasks: install-fail2ban.yml
- import_tasks: configure-fail2ban.yml
