- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- package:
    name: fail2ban
    state: present

- service:
    name: fail2ban
    state: started
    enabled: yes
  when: ansible_virtualization_type != 'docker'

- copy:
   src: fail2ban.local
   dest: /etc/fail2ban/fail2ban.local
   owner: root
   group: root
   mode: 0644
   backup: yes
  notify: restart fail2ban

- template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart fail2ban
