- name: Set up distro vars
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Install openssh package
  package:
    name: "{{ openssh_package }}"
    state: present

- name: Copy sshrc file
  copy:
    src: sshrc
    dest: /etc/ssh/sshrc
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Start openssh service
  service:
    name: "{{ openssh_service }}"
    state: started
    enabled: yes
  when: ansible_virtualization_type is not defined or ansible_virtualization_type != 'docker'
