- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- package: name={{ openssh_package }} state=present

- service: name={{ openssh_service }} state=started enabled=yes
