- name: Install haveged package
  ansible.builtin.package:
    name: haveged
    state: present

- name: Start haveged service
  ansible.builtin.service:
    name: haveged
    state: started
    enabled: true
  when: ansible_virtualization_type is not defined or ansible_virtualization_type != 'docker'
