- name: Install haveged package
  package:
    name: haveged
    state: present

- name: Start haveged service
  service:
    name: haveged
    state: started
    enabled: yes
  when: ansible_virtualization_type is not defined or ansible_virtualization_type != 'docker'
