- name: Install misc packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - htop
    - tree
    - git
    - strace
    - mlocate
    - diffstat
    - bash-completion
    - pwgen
    - lsof
    - multitail

- name: Install misc packages for Debian
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == 'Debian'
  loop:
    - debian-goodies
    - apt-transport-https
