- package: name={{ item }} state=present
  with_items:
  - htop
  - tree
  - git
  - strace
  - mlocate
  - diffstat
  - bash-completion
  - pwgen
  - lsof
  - multitail

- package: name=debian-goodies state=present
  when: ansible_os_family == 'Debian'
