- package:
    name: "{{ item }}"
    state: present
  with_items:
  - htop
  - tree
  - git
  - strace
  - mlocate
  - diffstat
  - bash-completion
  - pwgen
  - lsof

- package:
    name: "{{ item }}"
    state: present
  when: ansible_distribution_major_version != "8" and ansible_os_family != "RedHat"
  with_items:
  - multitail

- package:
    name: "{{ item }}"
    state: present
  when: ansible_os_family == 'Debian'
  with_items:
  - debian-goodies
  - apt-transport-https
