- hosts: 127.0.0.1
  user: root
  connection: local

  roles:
     - role: 'epel'
       when: ansible_os_family == 'RedHat'
     - role: 'etckeeper'
     - role: 'misc'
     - role: 'net'
     - role: 'screen'
     - role: 'ssh'
     - role: 'fail2ban'
     - role: 'vim'
     - role: 'postfix'
