- include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- dnf:
    name: "{{ epel_release_uri }}"
    state: present
  notify: update dnf cache
