- action: yum pkg=epel-release state=installed
  register: installed_epel_pkg

- copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 owner=root group=root mode=0644
  register: installed_epel_key

- command: yum -y makecache
  run_once: true
  when: installed_epel_pkg.changed or installed_epel_key.changed
