- yum: pkg={{ epel_release_uri }} state=present
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "default.yml"
  register: installed_epel_pkg

- copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 owner=root group=root mode=0644
  register: installed_epel_key

- command: yum -y makecache
  when: installed_epel_pkg.changed or installed_epel_key.changed
