- name: Set up distro vars
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: Install epel release
  ansible.builtin.dnf:
    name: "{{ epel_release_uri }}"
    state: present
  notify: Update dnf cache
