- name: Install screen package
  ansible.builtin.package:
    name: screen
    state: present

- name: Copy screenrc file
  ansible.builtin.copy:
    src: screenrc
    dest: /etc/screenrc
    owner: root
    group: root
    mode: 0644
    backup: true
