- name: Install screen package
  package:
    name: screen
    state: present

- name: Copy screenrc file
  copy:
    src: screenrc
    dest: /etc/screenrc
    owner: root
    group: root
    mode: 0644
    backup: yes
