- name: Install etckeeper packaqge
  ansible.builtin.package:
    name: etckeeper
    state: present

- name: Check for /etc/.git dir
  ansible.builtin.stat:
    path: /etc/.git
  register: etc_git

- name: Run etckeeper init
  ansible.builtin.command: etckeeper init
  when: not etc_git.stat.exists
  changed_when: false

- name: Force all notified handlers to run
  ansible.builtin.meta: flush_handlers

- name: Install /etc/.git/config
  ansible.builtin.template:
    src: gitconfig.j2
    dest: /etc/.git/config
    owner: root
    group: root
    mode: '0644'
