- name: Set up distro vars
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Remove exim package
  package:
    name: "{{ exim_package }}"
    state: absent

- name: Install mailx package
  package:
    name: "{{ mailx_package }}"
    state: present

- name: Install postfix package
  package:
    name: postfix
    state: present

- name: Install postfix-lmdb package
  package:
    name: postfix-lmdb
    state: present
  when: ansible_os_family == 'Debian' or ansible_distribution == 'Fedora'

- name: Start postfix service
  service:
    name: postfix
    state: started
    enabled: yes
  when: ansible_virtualization_type is not defined or ansible_virtualization_type != 'docker'

- name: Configure postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart postfix

- name: Add root mail alias
  lineinfile:
    path: /etc/aliases
    regexp: '^root:'
    line: "root: {{ root_mail_alias }}"
  notify: exec newaliases
